name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
  MarkdownLint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: markdownlint-cli
      uses: nosborn/github-action-markdown-cli@v1.1.1
      with:
        files: .
        args: './README.md ./docs/'
  UpdateMonitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        id: projectmetrics
        run: |
          yarn
          yarn build
          SRC_SIZE=($(du -s src/))
          SRC_FILES_COUNT=($(find src -type f | wc -l))
          echo "::set-env name=code_size::$SRC_SIZE"
          echo "::set-env name=code_files_count::$SRC_FILES_COUNT"
      - uses: ./
        name: Update Report for Files Size
        with:
          key: code-size
          value: ${{ env.code_size }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: ./
        name: Update Report for Files Count
        with:
          key: files-count
          value: ${{ env.code_files_count }}
          token: ${{ secrets.GITHUB_TOKEN }}
