name: Publish

on:
  release:
    types: [published]

jobs:
  ReleaseBuild:
    strategy:
      matrix:
        kind: ["linux", "windows"]
        include:
          - kind: linux
            os: ubuntu-latest
            target: linux-x64
          - kind: windows
            os: windows-latest
            target: win-x64
    runs-on: ${{ matrix.os }}
